const assert = require('assert');
const fs = require('fs');
const path = require('path');

const css = fs.readFileSync(path.join(__dirname, '..', 'css', 'styles.css'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(__dirname, '..', 'js', 'app.js'), 'utf8');

assert.ok(css.includes('@media (max-width: 900px)'), 'responsive layout should define tablet breakpoint');
assert.ok(css.includes('@media (max-width: 560px)'), 'responsive layout should define mobile breakpoint');
assert.ok(css.includes('.sidebar { background: var(--sidebar-bg); display: none;'), 'mobile sidebar should become a compact overlay');
assert.ok(css.includes('.main-content { margin-left: 0; max-width: 100%'), 'mobile content should use full width');
assert.ok(css.includes('overflow-x: hidden'), 'page should prevent accidental horizontal overflow');
assert.ok(css.includes('focus-visible'), 'interactive controls should expose visible keyboard focus');
assert.ok(css.includes('prefers-reduced-motion'), 'interface should respect reduced-motion preference');
assert.ok(css.includes('prefers-contrast: more'), 'interface should support increased contrast preference');
assert.ok(css.includes('.scoreboard .team-color'), 'live match scoreboard should have responsive team sizing');
assert.ok(css.includes('.commentary-box {\n        height: min(42vh, 300px)'), 'live commentary should adapt to short screens');
assert.ok(css.includes('@media (max-width: 420px)'), 'live match should have a compact phone breakpoint');
assert.ok(css.includes('.tactics-layout {\n        height: auto;\n        flex-direction: column;'), 'tactics should stack on narrower screens');
assert.ok(css.includes('.bench-list {\n        max-height: 280px;'), 'bench list should remain scrollable on tablets');
assert.ok(css.includes('.pitch-container {\n        min-height: 390px;'), 'pitch should preserve a usable mobile touch area');
assert.ok(css.includes('min-height: 44px;'), 'mobile controls should meet a comfortable touch target');
assert.ok(css.includes('touch-action: manipulation;'), 'mobile controls should avoid delayed touch activation');
assert.ok(css.includes('border-width: 2px'), 'alerts should have a non-color visual distinction');
assert.ok(html.includes('overflow-x: auto'), 'wide tables should have local horizontal scrolling');
assert.ok(html.includes('historicoFinanceiroMensal'), 'monthly finance table should be present');
assert.ok(html.includes('skip-link'), 'page should provide a skip link');
assert.ok(html.includes('id="conteudo-principal"'), 'main content should have a keyboard target');
assert.ok(html.includes('aria-label="Navegação principal do clube"'), 'main navigation should be labelled');
assert.ok(html.includes('aria-live="polite"'), 'messages should announce updates to assistive technology');
assert.ok(html.includes('selecionarJogadorParaTatica(jogador)'), 'tactics should offer tap selection for players');
assert.ok(html.includes('colocarJogadorSelecionadoNoCampo($event)'), 'tactics should offer tap placement on the pitch');
assert.ok(html.includes('retirarJogadorSelecionadoDoCampo(jogador)'), 'tactics should offer tap removal from the pitch');
assert.ok(html.includes('pausarPartidaManualmente()'), 'live match should expose a manual tactical pause');
assert.ok(html.includes('obterResumoPausaTatica().restantes'), 'tactical pause should show remaining substitutions');
assert.ok(html.includes('obterResumoPausaTatica().impedidos'), 'tactical pause should show unavailable players');
assert.ok(html.includes('obterStatusTaticaJogador(jogador)'), 'bench should show each player tactical status');
assert.ok(css.includes('.bench-status-disponivel'), 'bench should style available players distinctly');
assert.ok(css.includes('.bench-status-utilizado'), 'bench should style already used players distinctly');
assert.ok(html.includes('voltarParaPartidaAoVivo()'), 'paused match should offer a direct return action');
assert.ok(html.includes('class="live-match-context"'), 'other screens should show live match context');
assert.ok(css.includes('.live-match-context'), 'live match context should have a visible banner');
assert.ok(html.includes('posJogo.resumo.gestao.substituicoes'), 'post-match should report substitutions');
assert.ok(html.includes('posJogo.resumo.gestao.pausasTaticas'), 'post-match should report tactical pauses');
assert.ok(html.includes('historicoPartidas'), 'career screen should include match history');
assert.ok(css.includes('.career-match-history'), 'match history should have a responsive-friendly layout');
assert.ok(html.includes('historicoPartidasFiltro'), 'career history should expose match filters');
assert.ok(html.includes('obterHistoricoPartidasFiltrado()'), 'career history should render filtered matches');
assert.ok(html.includes('alternarDetalhesPartidaHistorico(partida)'), 'career history should allow expanding match details');
assert.ok(html.includes('partidaHistoricoAberta === partida'), 'career history should render expanded match details');
assert.ok(css.includes('.career-match-history-details'), 'expanded match details should have a dedicated layout');
assert.ok(html.includes('obterResumoHistoricoPartidas()'), 'career history should expose aggregate statistics');
assert.ok(css.includes('.career-history-summary'), 'career aggregate statistics should have a compact layout');
assert.ok(html.includes('obterResumoPorTemporada()'), 'career history should compare seasons');
assert.ok(css.includes('.career-season-summary'), 'season comparison should have a responsive grid');
assert.ok(html.includes('obterTendenciaCarreira()'), 'career history should expose performance trend');
assert.ok(css.includes('.career-trend-alta'), 'career trend should distinguish positive evolution');
assert.ok(html.includes('obterRecomendacoesCarreira()'), 'career history should expose practical recommendations');
assert.ok(css.includes('.career-recommendations'), 'career recommendations should have a responsive layout');
assert.ok(html.includes('aplicarRecomendacaoComoMeta(recomendacao)'), 'career recommendations should connect to board goals');
assert.ok(html.includes('obterProgressoMetaCarreira()'), 'career goal should expose live progress');
assert.ok(css.includes('.career-goal-progress'), 'career goal should have a progress panel');
assert.ok(html.includes('obterAvaliacaoDiretoriaCarreira()'), 'career should expose board evaluation');
assert.ok(css.includes('.career-board-evaluation-risco'), 'board evaluation should distinguish risk');
assert.ok(html.includes('responderEventoDiretoria(mensagemAberta'), 'messages should offer director response choices');
assert.ok(css.includes('.career-confidence'), 'director confidence should remain visible after responses');
assert.ok(html.includes('registrarAvaliacaoDiretoriaCarreira()'), 'career should allow recording board evaluations');
assert.ok(html.includes('career-board-history'), 'career should show board evaluation history');
assert.ok(html.includes('obterConfiancaDiretoria()'), 'career should expose board confidence');
assert.ok(css.includes('.career-confidence'), 'board confidence should have a visible indicator');
assert.ok(html.includes('obterMargemPlanejamentoDiretoria()'), 'career should expose planning margin');
assert.ok(css.includes('.career-planning-margin-curta'), 'planning margin should distinguish immediate pressure');
assert.ok(html.includes('obterOrientacaoInvestimentoEstrutural()'), 'infrastructure should show investment guidance');
assert.ok(css.includes('.structural-investment-prioridade'), 'investment guidance should distinguish priority mode');
assert.ok(html.includes('obterOrientacaoCategoriasBase()'), 'youth academy should show board guidance');
assert.ok(css.includes('.youth-director-proteger'), 'youth guidance should distinguish protection mode');
assert.ok(html.includes('sugestao.orientacao'), 'promotion suggestions should include board guidance');
assert.ok(html.includes('obterOrientacaoMercadoDiretoria()'), 'market should show board guidance');
assert.ok(css.includes('.market-director-preservar'), 'market guidance should distinguish cash preservation');
assert.ok(html.includes('obterOrientacaoFinanceiraDiretoria()'), 'finance should show board guidance');
assert.ok(css.includes('.finance-director-economizar'), 'finance guidance should distinguish liquidity priority');
assert.ok(html.includes('obterEstrategiaClube()'), 'dashboard should expose club strategy');
assert.ok(css.includes('.club-strategy-grid'), 'club strategy should have a compact summary grid');
assert.ok(html.includes('definirPrioridadeEstrategica'), 'dashboard should allow selecting a strategic priority');
assert.ok(css.includes('.strategy-selected'), 'selected strategic priority should be highlighted');
assert.ok(html.includes('obterFocoEstrategicoAtual()'), 'dashboard should prioritize the selected strategic focus');
assert.ok(css.includes('.club-strategy-focus'), 'dashboard should show the selected strategic focus');
assert.ok(html.includes('obterAlertaFocoEstrategico()'), 'dashboard should show focus-specific alerts');
assert.ok(css.includes('.club-strategy-alert-alerta'), 'focus alerts should distinguish risk');
assert.ok(html.includes('historicoDecisoesGestao'), 'career should show management decision history');
assert.ok(css.includes('.career-decision-history'), 'management decisions should have a history layout');
assert.ok(html.includes('season-management-report'), 'season ceremony should show a management report');
assert.ok(css.includes('.season-report-grid'), 'season management report should have a responsive grid');
assert.ok(html.includes('season-next-plan'), 'season ceremony should suggest the next season plan');
assert.ok(css.includes('.season-next-plan'), 'next season plan should have a responsive layout');
assert.ok(html.includes('club-strategy-briefing'), 'dashboard should show the board seasonal briefing');
assert.ok(css.includes('.club-strategy-briefing'), 'board briefing should have a visual treatment');
assert.ok(html.includes('metasTemporada'), 'dashboard should show categorized board goals');
assert.ok(css.includes('.board-goals-grid'), 'board goals should use a responsive grid');
assert.ok(html.includes('meta.progresso'), 'board goals should show live progress');
assert.ok(js.includes('ultimaReacaoMetasDia'), 'board should throttle strategic goal reactions');
assert.ok(js.includes("chave: 'meta_diretoria|"), 'strategic goal reactions should affect squad environment');
assert.ok(html.includes('season-report-goals'), 'season report should summarize goals by area');
assert.ok(html.includes('ambienteElenco'), 'season report should show squad environment');
assert.ok(html.includes('career-evolution-card'), 'career should show recent evolution comparison');
assert.ok(js.includes('obterEvolucaoCarreira'), 'career should expose season evolution data');
assert.ok(html.includes('career-total-card'), 'career should show cumulative trajectory');
assert.ok(js.includes('obterResumoCarreira'), 'career should expose cumulative data');
assert.ok(html.includes('career-club-card'), 'career should show performance by club');
assert.ok(js.includes('obterResumoCarreiraPorClube'), 'career should expose club breakdown');
assert.ok(html.includes('career-filter-tabs'), 'career should provide history filters');
assert.ok(js.includes('definirFiltroCarreira'), 'career filters should be controlled by the app');
assert.ok(html.includes('grouped-nav'), 'main navigation should be organized in groups');
assert.ok(js.includes('alternarGrupoMenu'), 'navigation groups should be collapsible');
assert.ok(html.includes('mobile-menu-bar'), 'mobile navigation should have a compact top bar');
assert.ok(js.includes('alternarMenuMobile'), 'mobile navigation should be toggleable');
assert.ok(css.includes('.dashboard-v2 .club-strategy-panel'), 'mobile dashboard should have a compact strategy panel');
assert.ok(css.includes('.dashboard-v2 .dashboard-panel'), 'mobile dashboard panels should use compact spacing');
assert.ok(css.includes('.calendar-day-row { grid-template-columns: minmax(0, 1fr) !important;'), 'calendar rows should stack on mobile');
assert.ok(html.includes('calendar-filters'), 'calendar filters should be identifiable for mobile layout');
assert.ok(html.includes('irParaFocoEstrategico()'), 'focus alerts should offer direct navigation');

console.log('responsive_layout.test.js passed');
