const fs=require('fs'),path=require('path'); const root=path.resolve(__dirname,'..');
const pf=path.join(root,'data','jogadores.json'), sf=path.join(root,'data','elencos_fontes_2026.json');
const old=JSON.parse(fs.readFileSync(pf,'utf8')), src=JSON.parse(fs.readFileSync(sf,'utf8'));
const abc=new Set(JSON.parse(fs.readFileSync(path.join(root,'data','clubes.json'),'utf8')).filter(c=>['A','B','C'].includes(c.divisao)).map(c=>String(c.id)));
const backup=pf+'.backup-final-'+Date.now(); fs.copyFileSync(pf,backup);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const validPos=new Set(['GOL','ZAG','LAT','VOL','MEI','ATA']); const oldBy=new Map(); old.forEach(p=>{const k=norm(p.nome);if(!oldBy.has(k))oldBy.set(k,[]);oldBy.get(k).push(p)});
function overallAlvo(r){const v=Number(r.valorMercado)||0;const idade=Number(r.idade)||25;let alvo=v>0?Math.round(48+Math.log10(Math.max(v,25000))*7.2):58;if(idade<=21)alvo-=2;else if(idade>=34)alvo-=Math.min(5,Math.floor((idade-33)/2));return Math.max(52,Math.min(91,alvo));}
function atributosPara(r){const o=overallAlvo(r),p=r.posicao,a={finalizacao:o,passe:o,marcacao:o,velocidade:o,fisico:o,reflexo:40,posicionamento:o,distribuicao:o,penalti:o,escanteio:o,cobrador:o};if(p==='GOL'){a.reflexo=o+2;a.distribuicao=o-3;a.finalizacao=30;a.marcacao=30;a.velocidade=o-12;}else if(p==='ZAG'){a.marcacao=o+3;a.posicionamento=o+2;a.finalizacao=o-10;a.velocidade=o-5;}else if(p==='LAT'){a.velocidade=o+3;a.passe=o+1;}else if(p==='VOL'){a.marcacao=o+2;a.passe=o+2;a.finalizacao=o-5;}else if(p==='MEI'){a.passe=o+3;a.finalizacao=o+2;a.marcacao=o-8;}else{a.finalizacao=o+3;a.velocidade=o+2;a.marcacao=o-10;}return Object.fromEntries(Object.entries(a).map(([k,n])=>[k,Math.max(25,Math.min(99,Math.round(n)))]));}
const used=new Set(old.filter(p=>!abc.has(String(p.clubeId))).map(p=>norm(p.nome))); const out=old.filter(p=>!abc.has(String(p.clubeId))); const usedIds=new Set(out.map(p=>String(p.id))); let id=Math.max(...old.map(p=>Number(p.id)),0)+1;
for(const r of src){const base=String(r.nome).trim();let match=(oldBy.get(norm(base))||[]).find(p=>abc.has(String(p.clubeId))&&p.posicao===r.posicao&&Math.abs(Number(p.idade)-Number(r.idade||p.idade))<=1&&!usedIds.has(String(p.id)));const p=match?{...match}:{id:id++,clubeId:r.clubId,nome:base,posicao:r.posicao,idade:r.idade||25,salario:50000,salarioDesejado:55000,potencial:70,origem:'confirmado_fonte_2026'};usedIds.add(String(p.id));p.clubeId=r.clubId;p.nome=base;p.posicao=r.posicao;p.idade=r.idade||p.idade;p.valorMercadoFonte=r.valorMercado||null;p.atributos=atributosPara(r);p.potencial=Math.max(overallAlvo(r),Math.min(99,overallAlvo(r)+(Number(r.idade)<=25?8:3)));p.origem='confirmado_fonte_2026';out.push(p)}
fs.writeFileSync(pf,JSON.stringify(out,null,2)+'\n'); console.log(JSON.stringify({antes:old.length,depois:out.length,fonte:src.length,backup},null,2));
