const fs=require('fs'),path=require('path'); const root=path.resolve(__dirname,'..');
const pf=path.join(root,'data','jogadores.json'), sf=path.join(root,'data','elencos_fontes_2026.json');
const old=JSON.parse(fs.readFileSync(pf,'utf8')), src=JSON.parse(fs.readFileSync(sf,'utf8'));
const avaliacoes=JSON.parse(fs.readFileSync(path.join(root,'data','avaliacoes_individuais_2026.json'),'utf8'));
const abc=new Set(JSON.parse(fs.readFileSync(path.join(root,'data','clubes.json'),'utf8')).filter(c=>['A','B','C'].includes(c.divisao)).map(c=>String(c.id)));
const backup=pf+'.backup-final-'+Date.now(); fs.copyFileSync(pf,backup);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const avaliacaoPorIdentidade=new Map(avaliacoes.map(a=>[[String(a.clubeId),norm(a.nome)].join('|'),a]));
const validPos=new Set(['GOL','ZAG','LAT','VOL','MEI','ATA']); const oldBy=new Map(); old.forEach(p=>{const k=norm(p.nome);if(!oldBy.has(k))oldBy.set(k,[]);oldBy.get(k).push(p)});
function valorFonteNormalizado(valor){let v=Number(valor)||0;return v>0?Math.round(v/1000):0;}
function overallAlvo(r){const avaliacao=avaliacaoPorIdentidade.get([String(r.clubId),norm(r.nome)].join('|'));if(avaliacao)return avaliacao.overall;const v=valorFonteNormalizado(r.valorMercado);const idade=Number(r.idade)||25;const baseDivisao={A:72,B:67,C:62}[r.divisao]||58;const ajusteDivisao={A:8,B:-5,C:-3}[r.divisao]||0;let alvo=v>0?Math.round(70+Math.log10(Math.max(v,1000000)/1000000)*8)+ajusteDivisao:baseDivisao;if(idade<=21)alvo-=2;else if(idade>=34)alvo-=Math.min(5,Math.floor((idade-33)/2));return Math.max(52,Math.min(91,alvo));}
function atributosPara(r){const o=overallAlvo(r),p=r.posicao,a={finalizacao:o,passe:o,marcacao:o,velocidade:o,fisico:o,reflexo:40,posicionamento:o,distribuicao:o,penalti:o,escanteio:o,cobrador:o};if(p==='GOL'){a.reflexo=o+2;a.distribuicao=o-3;a.finalizacao=30;a.marcacao=30;a.velocidade=o-12;}else if(p==='ZAG'){a.marcacao=o+3;a.posicionamento=o+2;a.finalizacao=o-10;a.velocidade=o-5;}else if(p==='LAT'){a.velocidade=o+3;a.passe=o+1;}else if(p==='VOL'){a.marcacao=o+2;a.passe=o+2;a.finalizacao=o-5;}else if(p==='MEI'){a.passe=o+3;a.finalizacao=o+2;a.marcacao=o-8;}else{a.finalizacao=o+3;a.velocidade=o+2;a.marcacao=o-10;}const manual=avaliacaoPorIdentidade.has([String(r.clubId),norm(r.nome)].join('|'));if(!manual){const keys=['finalizacao','passe','marcacao','velocidade','fisico'];let seed=0;for(const ch of String(r.nome||''))seed=(seed*31+ch.charCodeAt(0))>>>0;keys.forEach((key,i)=>{const variacao=((seed>>>i*3)%5)-2;a[key]+=variacao;});}return Object.fromEntries(Object.entries(a).map(([k,n])=>[k,Math.max(25,Math.min(99,Math.round(n)))]));}
const used=new Set(old.filter(p=>!abc.has(String(p.clubeId))).map(p=>norm(p.nome))); const out=old.filter(p=>!abc.has(String(p.clubeId))); const usedIds=new Set(out.map(p=>String(p.id))); const usedIdentity=new Set(); let id=Math.max(...old.map(p=>Number(p.id)),0)+1;
for(const r of src){const base=String(r.nome).trim(),identity=[norm(base),r.idade||25,r.posicao,r.clubId].join('|');if(usedIdentity.has(identity))continue;usedIdentity.add(identity);let match=(oldBy.get(norm(base))||[]).find(p=>abc.has(String(p.clubeId))&&p.posicao===r.posicao&&Math.abs(Number(p.idade)-Number(r.idade||p.idade))<=1&&!usedIds.has(String(p.id)));const p=match?{...match}:{id:id++,clubeId:r.clubId,nome:base,posicao:r.posicao,idade:r.idade||25,salario:50000,salarioDesejado:55000,potencial:70,origem:'confirmado_fonte_2026'};const avaliacao=avaliacaoPorIdentidade.get([String(r.clubId),norm(base)].join('|'));usedIds.add(String(p.id));p.clubeId=r.clubId;p.nome=base;p.posicao=r.posicao;p.idade=r.idade||p.idade;p.valorMercadoFonte=valorFonteNormalizado(r.valorMercado)||null;p.atributos=atributosPara(r);p.overallBase=overallAlvo(r);p.overallAtual=p.overallBase;p.potencial=avaliacao?avaliacao.potencial:Math.max(overallAlvo(r),Math.min(99,overallAlvo(r)+(Number(r.idade)<=25?8:3)));p.reputacaoIndividual=avaliacao?avaliacao.reputacao:(Number(p.idade)<=23?'promissor':'profissional_consolidado');p.origem=avaliacao?'manual_2026':'confirmado_fonte_2026';out.push(p)}
out.forEach(p=>{const avaliacao=avaliacaoPorIdentidade.get([String(p.clubeId),norm(p.nome)].join('|'));if(avaliacao&&avaliacao.salario)p.salario=avaliacao.salario;});
fs.writeFileSync(pf,JSON.stringify(out,null,2)+'\n'); console.log(JSON.stringify({antes:old.length,depois:out.length,fonte:src.length,backup},null,2));
